In [150]:
import logging
import time
from datetime import datetime
import backtrader as bt
import tushare as ts
import os
import pandas as pd
from datetime import date
from dateutil.relativedelta import relativedelta

ts.set_token('adb0ef8900a40075aaeab987278f80e49701afcd29eec9f5693428db')
pro = ts.pro_api()

In [69]:
stocks1={'002459.SZ':'2010-08-10','002709.SZ':'2014-01-23','002812.SZ':'2016-09-14','002821.SZ':'2016-11-18','300450.SZ':'2015-05-18','300750.SZ':'2018-06-11','300775.SZ':'2019-05-21','300782.SZ':'2019-06-18','300896.SZ':'2020-09-28'}
stocks2={'000002.SZ':'1991-01-29','000063.SZ':'1997-11-18','000333.SZ':'2013-09-18','000338.SZ':'2007-04-30','000568.SZ':'1994-05-09','600030.SH':'2003-01-06','600036.SH':'2002-04-09','600096.SH':'1997-07-09','600885.SH':'1996-02-05','600887.SH':'1996-03-12'}

In [188]:
#获取序列数据保存到文件夹
def get_single_kdata(code, start, end='2023-02-08'):
    df = ts.pro_bar(ts_code=code, start_date=start, end_date=end,asset='E',adj='qfq',freq='D')
    #df['trade_date']=df['trade_date']+' 00:00:00'
    df['trade_date'] =df['trade_date'].apply(lambda x:x+' 00:01:00')
    '''df['trade_date'] =df['trade_date'].apply(lambda x:datetime.strptime(x+' 00:00:00',"%Y%m%d %H:%M:%S"))'''
    df['date']=pd.to_datetime(df['trade_date'],format="%Y%m%d %H:%M:%S")
    df['volume']=df['vol']
    df['openinterest'] = 0
    df.set_index('date',drop=True,inplace=True)
    return df[[ 'open', 'high', 'low', 'close', 'volume', 'openinterest']]


for stk in stocks1.keys():
    bt_start = datetime.strptime(stocks1[stk],"%Y-%m-%d") + relativedelta(months=+6)
    bt_start=bt_start.strftime("%Y%m%d")
    #print(get_single_kdata(stk,start=bt_start))
    get_single_kdata(stk,start=bt_start).to_csv('data/stocks1/'+stk+'.csv')
    #print(get_single_kdata('002459.SZ',start=bt_start))
for stk in stocks2.keys():
    bt_start = datetime.strptime(stocks2[stk],"%Y-%m-%d") + relativedelta(months=+6)
    bt_start=bt_start.strftime("%Y%m%d")
    get_single_kdata(stk,start='2010-01-01').to_csv('data/stocks2/'+stk+'.csv')
    #print(get_single_kdata('002459.SZ',start=bt_start))

In [187]:
#单独测试，可以忽略
def get_single_kdata(code, start, end='2023-02-08'):
    df = ts.pro_bar(ts_code=code, start_date=start, end_date=end,asset='E',adj='qfq',freq='D')
    df['trade_date'] =df['trade_date'].apply(lambda x:x+' 00:01:00')
    '''df['trade_date'] =df['trade_date'].apply(lambda x:datetime.strptime(x+' 00:00:00',"%Y%m%d %H:%M:%S"))'''
    df['date']=pd.to_datetime(df['trade_date'],format="%Y%m%d %H:%M:%S")
    df['volume']=df['vol']
    df['openinterest'] = 0
    print(df.info())
    print(df)
    df.set_index('date',drop=True,inplace=True)

    return df[[ 'open', 'high', 'low', 'close', 'volume', 'openinterest']]

stk='002459.SZ'
'''bt_start = datetime.strptime(stocks1[stk],"%Y-%m-%d") + relativedelta(months=+6)
bt_start=bt_start.strftime("%Y%m%d")'''
get_single_kdata(stk,start=bt_start)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2944 entries, 0 to 2943
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ts_code       2944 non-null   object
 1   trade_date    2944 non-null   object
 2   open          2944 non-null   float64
 3   high          2944 non-null   float64
 4   low           2944 non-null   float64
 5   close         2944 non-null   float64
 6   pre_close     2944 non-null   float64
 7   change        2944 non-null   float64
 8   pct_chg       2944 non-null   float64
 9   vol           2944 non-null   float64
 10  amount        2944 non-null   float64
 11  date          2944 non-null   datetime64[ns]
 12  volume        2944 non-null   float64
 13  openinterest  2944 non-null   int64
dtypes: datetime64[ns](1), float64(10), int64(1), object(2)
memory usage: 322.1+ KB
None
        ts_code         trade_date     open     high      low    close  \
0     002459.SZ  20230208 00:01:00  61.5800  61.9500  60.8500  60.9000
1     002459.SZ  20230207 00:01:00  61.7000  62.8200  61.0900  61.5800
2     002459.SZ  20230206 00:01:00  62.2000  63.1200  61.0800  61.7000
3     002459.SZ  20230203 00:01:00  63.2500  63.4200  61.0000  62.3200
4     002459.SZ  20230202 00:01:00  64.7400  64.9500  63.1200  63.3500
...         ...                ...      ...      ...      ...      ...
2939  002459.SZ  20100816 00:01:00  16.4216  17.0924  16.2069  16.9046
2940  002459.SZ  20100813 00:01:00  16.6363  16.8778  16.0996  16.5289
2941  002459.SZ  20100812 00:01:00  17.9779  18.1228  16.5289  16.7436
2942  002459.SZ  20100811 00:01:00  18.0316  19.5557  17.7579  18.2945
2943  002459.SZ  20100810 00:01:00  16.6363  19.9903  16.6363  19.5879

      pre_close  change  pct_chg        vol        amount                date  \
0       61.5800 -0.6800  -1.1043   84540.63  5.169774e+05 2023-02-08 00:01:00
1       61.7000 -0.1200  -0.1945  118353.12  7.304256e+05 2023-02-07 00:01:00
2       62.3200 -0.6200  -0.9949  116369.69  7.172646e+05 2023-02-06 00:01:00
3       63.3500 -1.0300  -1.6259  133390.35  8.271052e+05 2023-02-03 00:01:00
4       65.0500 -1.7000  -2.6134  180402.82  1.149631e+06 2023-02-02 00:01:00
...         ...     ...      ...        ...           ...                 ...
2939    16.5289  0.3757   2.2730   64676.13  2.014148e+05 2010-08-16 00:01:00
2940    16.7436 -0.2147  -1.2823   72628.66  2.224768e+05 2010-08-13 00:01:00
2941    18.2945 -1.5509  -8.4774  133805.60  4.338538e+05 2010-08-12 00:01:00
2942    19.5879 -1.2934  -6.6031  209026.78  7.206275e+05 2010-08-11 00:01:00
2943    12.0532  7.5347  62.5120  305481.00  1.011385e+06 2010-08-10 00:01:00

         volume  openinterest
0      84540.63             0
1     118353.12             0
2     116369.69             0
3     133390.35             0
4     180402.82             0
...         ...           ...
2939   64676.13             0
2940   72628.66             0
2941  133805.60             0
2942  209026.78             0
2943  305481.00             0

[2944 rows x 14 columns]

,open,high,low,close,volume,openinterest
date,,,,,,
2023-02-08 00:01:00,61.5800,61.9500,60.8500,60.9000,84540.63,0
2023-02-07 00:01:00,61.7000,62.8200,61.0900,61.5800,118353.12,0
2023-02-06 00:01:00,62.2000,63.1200,61.0800,61.7000,116369.69,0
2023-02-03 00:01:00,63.2500,63.4200,61.0000,62.3200,133390.35,0
2023-02-02 00:01:00,64.7400,64.9500,63.1200,63.3500,180402.82,0
...,...,...,...,...,...,...
2010-08-16 00:01:00,16.4216,17.0924,16.2069,16.9046,64676.13,0
2010-08-13 00:01:00,16.6363,16.8778,16.0996,16.5289,72628.66,0
2010-08-12 00:01:00,17.9779,18.1228,16.5289,16.7436,133805.60,0
2010-08-11 00:01:00,18.0316,19.5557,17.7579,18.2945,209026.78,0
2010-08-10 00:01:00,16.6363,19.9903,16.6363,19.5879,305481.00,0

In [109]:
#初始化回测模型
cerebro = bt.Cerebro()
# 设定初始资金
startcash=1000000
cerebro.broker.setcash(startcash)
# 策略执行前的资金
print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
cerebro.run()
# 策略执行后的资金
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

Starting Portfolio Value: 1000000.00
Final Portfolio Value: 1000000.00

In [220]:
#数据注入与模型主体
data=bt.feeds.PandasData(dataname=stkdf)
cerebro.adddata(data)

cerebro.addstrategy(MAStrategy)

#运行回测系统
cerebro.run()
#获取回测结束后的总资金
portvalue = cerebro.broker.getvalue()
pnl = portvalue - startcash
#打印结果
print(f'总资金: {round(portvalue,2)}')

ValueError: time data '2022-08-22' does not match format '%Y-%m-%d %H:%M:%S'

In [75]:
class MAStrategy(bt.Strategy):
    def next(self):
        # 记录收盘价
        self.log('Close, %.2f' % self.dataclose[0])
        s=5
        l=10
        self.sma_s = bt.indicators.SimpleMovingAverage(self.datas[0], period=s)
        self.sma_l = bt.indicators.SimpleMovingAverage(self.datas[0], period=l)
        # 是否正在下单，如果是的话不能提交第二次订单
        if self.order:
            return

        # 是否已经买入
        if not self.position:

            # 还没买，如果 MA5 > MA10 说明涨势，买入
            if self.sma_s[0] > self.sma_l[0]:
                self.log('BUY CREATE, %.2f' % self.dataclose[0])
                self.order = self.buy()

        else:
            # 已经买了，如果 MA5 < MA10 ，说明跌势，卖出
            if self.sma_s[0] < self.sma_l[0]:
                self.log('SELL CREATE, %.2f' % self.dataclose[0])
                self.order = self.sell()

In [214]:
#akshare测试
import akshare as ak
stkdf=ak.stock_zh_a_daily(symbol='sz002459',start_date='20100810',end_date='20230228',adjust='qfq')
stkdf['date']=pd.to_datetime(stkdf['date'],format='%Y-%m-%d %H:%M:%S')
stkdf=stkdf.set_index('date')
stkdf

,open,high,low,close,volume,outstanding_share,turnover
date,,,,,,,
2010-08-10,16.64,19.99,16.64,19.59,30548100.0,3.440000e+07,0.888026
2010-08-11,18.04,19.56,17.76,18.30,20902678.0,3.440000e+07,0.607636
2010-08-12,17.98,18.13,16.53,16.75,13380560.0,3.440000e+07,0.388970
2010-08-13,16.64,16.88,16.10,16.53,7262866.0,3.440000e+07,0.211130
2010-08-16,16.43,17.10,16.21,16.91,6467613.0,3.440000e+07,0.188012
...,...,...,...,...,...,...,...
2023-02-22,59.60,61.00,58.50,58.80,11629907.0,2.343687e+09,0.004962
2023-02-23,59.00,60.82,58.61,60.13,18632038.0,2.343687e+09,0.007950
2023-02-24,60.13,60.30,58.48,58.89,12851834.0,2.343687e+09,0.005484
2023-02-27,58.88,62.55,58.50,61.28,23982759.0,2.343687e+09,0.010233
2023-02-28,61.00,61.39,59.90,61.12,13799113.0,2.343687e+09,0.005888