In [1]:
import pandas as pd
import importlib
import os
import sys
sys.path.append('/data/code/finhack')
from astock.astock import AStock

In [2]:
#获取股票代码列表
AStock.getStockCodeList()

        ts_code
0     600860.SH
1     600701.SH
2     000001.SZ
3     000002.SZ
4     000088.SZ
...         ...
5354  871694.BJ
5355  688478.SH
5356  301307.SZ
5357  301360.SZ
5358  833394.BJ

[5359 rows x 1 columns]

In [5]:
# 获取股票日线行情,多股
# def getStockDailyPrice(code_list=[],where="",startdate='',enddate='',fq='hfq',db='tushare',cache=True):

AStock.getStockDailyPrice(code_list=['002624.SZ','000001.SZ'],
                          where="open<close",startdate="20200101",enddate="20220101",fq="qfq",cache=False)

all completed

,ts_code,trade_date,open,high,low,close,pre_close,change,returns,volume,amount,name,vwap,stop,upLimit,downLimit,adj_factor
0,000001.SZ,20200102,15.953348,16.240796,15.857532,16.164143,15.761716,0.42,2.5532,1530231.87,2571196.482,平安银行,16.802659,0,17.342679,14.190335,109.169
1,000001.SZ,20200103,16.231214,16.585733,16.212051,16.461172,16.164143,0.31,1.8376,1116194.81,1914495.474,平安银行,17.151983,0,17.783432,14.544854,109.169
2,000001.SZ,20200106,16.298285,16.614478,16.202469,16.355775,16.461172,-0.11,-0.6403,862083.50,1477930.193,平安银行,17.143701,0,18.109206,14.813139,109.169
3,000001.SZ,20200107,16.413264,16.556988,16.240796,16.432428,16.355775,0.08,0.4687,728607.56,1247047.135,平安银行,17.115484,0,17.994227,14.717323,109.169
4,000001.SZ,20200113,16.049164,16.317448,15.915022,16.279122,15.991674,0.30,1.7975,872133.36,1468271.683,平安银行,16.835403,0,17.591800,14.391549,109.169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,002624.SZ,20211221,17.874664,18.444447,17.773573,17.966564,17.920614,0.05,0.2564,503773.16,988925.430,完美世界,19.630371,0,19.712675,16.128553,3.143
235,002624.SZ,20211222,18.380117,19.023421,18.040085,18.665009,17.966564,0.76,3.8875,598750.91,1213311.994,完美世界,20.264052,0,19.767816,16.174503,3.143
236,002624.SZ,20211223,18.545538,19.243982,18.380117,18.701769,18.665009,0.04,0.1969,414474.69,848515.579,完美世界,20.472072,0,20.530591,16.799427,3.143
237,002624.SZ,20211224,18.701769,19.482924,18.563918,19.133702,18.701769,0.47,2.3096,471147.08,982009.479,完美世界,20.842949,0,20.576541,16.836187,3.143
238,002624.SZ,20211230,17.553012,18.931520,17.534632,18.619058,17.608152,1.10,5.7411,607284.74,1216214.642,完美世界,20.027090,0,19.372643,15.843661,3.143

In [6]:
# 获取股票日线行情,单股
# def getStockDailyPriceByCode(code_list=[],where="",startdate='',enddate='',fq='hfq',db='tushare',cache=True):
AStock.getStockDailyPriceByCode(code='002624.SZ',
                          where="open<close",startdate="20200101",enddate="20220101",fq="qfq",cache=False)

,ts_code,trade_date,open,high,low,close,pre_close,change,returns,volume,amount,name,vwap,stop,upLimit,downLimit,adj_factor
0,002624.SZ,20200102,26.979307,29.428114,26.470149,29.428114,26.755035,4.41,9.9909,197866.42,930274.358,完美世界,47.015270,0,29.428114,24.081956,2.073
1,002624.SZ,20200103,29.846351,31.143491,29.106860,30.106991,29.428114,1.12,2.3069,231846.23,1142058.168,完美世界,49.259292,0,32.373956,26.488333,2.073
2,002624.SZ,20200106,28.185526,30.464614,27.943070,29.640263,30.106991,-0.77,-1.5502,287824.63,1398850.009,完美世界,48.600773,0,33.119509,27.094474,2.073
3,002624.SZ,20200107,29.549342,31.416254,29.264456,30.852544,29.640263,2.00,4.0900,213501.10,1063976.932,完美世界,49.834726,0,32.604289,26.676237,2.073
4,002624.SZ,20200113,28.003684,28.585579,27.615754,28.367368,27.973377,0.65,1.4085,215536.59,1002059.227,完美世界,46.491372,0,30.773746,25.179070,2.073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,002624.SZ,20211221,17.874664,18.444447,17.773573,17.966564,17.920614,0.05,0.2564,503773.16,988925.430,完美世界,19.630371,0,19.712675,16.128553,3.143
235,002624.SZ,20211222,18.380117,19.023421,18.040085,18.665009,17.966564,0.76,3.8875,598750.91,1213311.994,完美世界,20.264052,0,19.767816,16.174503,3.143
236,002624.SZ,20211223,18.545538,19.243982,18.380117,18.701769,18.665009,0.04,0.1969,414474.69,848515.579,完美世界,20.472072,0,20.530591,16.799427,3.143
237,002624.SZ,20211224,18.701769,19.482924,18.563918,19.133702,18.701769,0.47,2.3096,471147.08,982009.479,完美世界,20.842949,0,20.576541,16.836187,3.143
238,002624.SZ,20211230,17.553012,18.931520,17.534632,18.619058,17.608152,1.10,5.7411,607284.74,1216214.642,完美世界,20.027090,0,19.372643,15.843661,3.143

In [7]:
#获取指数权重
#get_index_weights(idx_code="000001.SH", date="20220101")
from astock.indexHelper import indexHelper
indexHelper.get_index_weights(idx_code="000001.SH", date="20220101")

          ts_code   con_code trade_date weight
149192  600058.SH  600058.SH   20211231  0.021
149193  688228.SH  688228.SH   20211231  0.005
149194  600328.SH  600328.SH   20211231  0.033
149195  600675.SH  600675.SH   20211231  0.038
149196  688208.SH  688208.SH   20211231  0.074
...           ...        ...        ...    ...
150937  603100.SH  603100.SH   20211231  0.017
150938  600770.SH  600770.SH   20211231  0.022
150939  600141.SH  600141.SH   20211231  0.088
150940  600234.SH  600234.SH   20211231  0.006
150941  601128.SH  601128.SH   20211231  0.038

[1750 rows x 4 columns]

In [10]:
from astock.market import market

#market.load_dividend()    #将分红送股数据加入缓存
#market.load_price()       #将行情数据加入缓存

#从缓存中获取单日股票行情

ts_code='301138.SZ'
market.get_price(ts_code,'20230414',client=None)

{'ts_code': '301138.SZ',
 'open': 29.72,
 'high': 30.1,
 'low': 28.9,
 'close': 30.0,
 'volume': 35514.71,
 'amount': 104767.484,
 'name': '华研精机',
 'vwap': 29.499735321016185,
 'stop': 0,
 'upLimit': 36.16,
 'downLimit': 24.1}