In [1]:
import pandas as pd
import importlib
import os
import sys
sys.path.append('/data/code/finhack')

In [11]:
from factors.indicatorCompute import indicatorCompute
from factors.preCheck import preCheck
preCheck.checkIndicatorsChange()
indicatorCompute.computeFactorByStock(ts_code='002624.SZ',factor_name="xx1_8_4_1")

检测因子函数变动---Start---
检测因子函数变动---End---

,ts_code,trade_date,open,high,low,close,pre_close,change,returns,volume,...,stop,upLimit,downLimit,adj_factor,xx1,xx2,xx3,xx1_8_4_1,xx2_8_4_1,xx3_8_4_1
0,002624.SZ,20111028,22.0100,25.6000,22.0000,25.0800,11.2000,13.88,123.9300,190533.54,...,0,12.3200,10.0800,1,xx1,8,22.0100,None,NaN,NaN
1,002624.SZ,20111031,23.9900,25.3000,23.3000,24.3900,25.0800,-0.69,-2.7500,140907.98,...,0,27.5900,22.5700,1,xx1,8,23.9900,xx1,8.0,22.0100
2,002624.SZ,20111101,23.5900,26.3800,23.4500,25.2000,24.3900,0.81,3.3200,131812.13,...,0,26.8300,21.9500,1,xx1,8,23.5900,xx1,8.0,23.9900
3,002624.SZ,20111102,24.2500,25.7300,23.9400,25.6600,25.2000,0.46,1.8300,90191.79,...,0,27.7200,22.6800,1,xx1,8,24.2500,xx1,8.0,23.5900
4,002624.SZ,20111103,26.0000,26.3000,24.3300,24.3700,25.6600,-1.29,-5.0300,98454.70,...,0,28.2300,23.0900,1,xx1,8,26.0000,xx1,8.0,24.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2406,002624.SZ,20230425,72.5382,78.1812,71.2386,76.6422,74.4534,0.64,2.9398,1620518.77,...,0,81.9090,66.9978,3.42,xx1,8,72.5382,xx1,8.0,70.4520
2407,002624.SZ,20230426,75.2400,76.9500,71.1702,73.7010,76.6422,-0.86,-3.8376,1255162.31,...,0,84.3030,68.9814,3.42,xx1,8,75.2400,xx1,8.0,72.5382
2408,002624.SZ,20230427,71.6832,71.7858,66.8268,68.4684,73.7010,-1.53,-7.0998,1135408.07,...,0,81.0882,66.3480,3.42,xx1,8,71.6832,xx1,8.0,75.2400
2409,002624.SZ,20230428,68.4684,75.3084,68.4684,74.9664,68.4684,1.90,9.4905,1357545.98,...,0,75.3084,61.6284,3.42,xx1,8,68.4684,xx1,8.0,71.6832
2410,002624.SZ,20230504,75.2400,80.3700,72.2646,78.3522,74.9664,0.99,4.5164,1532381.57,...,0,82.4562,67.4766,3.42,xx1,8,75.2400,xx1,8.0,68.4684

In [15]:
#获取指标详细信息
indicators,function_name,code,return_fileds=indicatorCompute.getFactorInfo('xx1')
print(indicators)
print(function_name)
print(code)
print(return_fileds)

myfactors
xx123
    def xx123(df,p):

        df['xx1']=p[0]

        df['xx2']=p[1]

        df['xx3']=df['open']

        return df

['xx1', 'xx2', 'xx3']

In [28]:
#def calc(formula='',df=pd.DataFrame(),name="alpha",check=False,replace=False):
from factors.alphaEngine import alphaEngine
alphaEngine.calc(formula="$open+$pe_0",name="alpha",check=True)

ts_code    trade_date
000001.SZ  20000104       54.6344
           20000105       55.0174
           20000106       56.1493
           20000107       58.6723
           20000110       60.6805
                           ...
873593.BJ  20230425       88.0874
           20230426       80.9770
           20230427       82.0732
           20230428       85.6878
           20230504      100.4154
Length: 12861489, dtype: float64